### ISSUE TITLE
Need help installing this

### ISSUE THREAD

**Issue by clayfink** [mattilyra/LSH#1]
fairly new to Python. What;s the easiest way to install this package. I don't see a setyp.py, so it's not clear what I need to do. I'm running OSX 10.8.5.

Thanks! I've implemented near-duplicate detection using LSH in Java, but my new code base ins in Python, so this would help a lot.

**Comment by mattilyra** [comment]
Hi

| fixed a few issues with the library and added a setup script.

If you need something more scalable for similarity scoring you might want to have a look at the gensim and the `similarities.docsim` module there.

**Comment by clayfink** [comment]
Thanks! I will check it out.

Clay
