### ISSUE TITLE
Is it possible to extend this project for document file formats like PDF, DOCX

### ISSUE THREAD

**Issue by abhinavbom** [mattilyra/LSH#11]
Wanted to see if the current project can be extended to popular document formats like pdf, docx etc.

**Comment by mattilyra** [comment]
As long as you have some way of extracting the content from the PDFs and DOCX files the method will work. I don't intend to integrate a PDF or DOCX parser to `lsh` though but there are a number of python libraries for handling those documents

For PDFs
https://pypi.python.org/pypi/PyPDF2
http://www.unixuser.org/~euske/python/pdfminer/index.html

For DOCX
https://python-docx.readthedocs.io/en/latest/


I have not used any one of the above libraries though.
