### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by nishitd** [mattilyra/LSH#12]
I am using Python 2.7.15 and after setup I get the following error when I try to `from lsh import minhash`. 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lsh/minhash.py", line 9, in <module>
    from .cMinhash import minhash_32, minhash_64
ImportError: No module named cMinhash
```

**Comment by mattilyra** [comment]
Hi nishitd,

Python 2 is not supported. It may work by accident, but not by design. If
possible you should use python 3.6

Best, Matti
