### ISSUE TITLE
Unable to install on Mojave (10.14.2) or Ubuntu

### ISSUE THREAD

**Issue by EggsBenedict** [mattilyra/LSH#14]
This implementation has been working astonishingly well! Such a great resource and explanation of everything.  ~I've been running this on a Windows 10 box and realized that the number of candidate duplicates aren't responding bands / duplicates - you can specify, for example 128 bands but cache.py will override that.  i.e. setting 16 bands and 128 seeds will clear your example code ValueError but will raise an error from line 35 of cache.py.  I was wondering if it was a windows thing~ (edit: this was my issue). and tried to install on my Mac and have been beating my head against the wall with the error below.  Any chance you've encountered something like this before?

I've updated xcode / command line tools / gcc but am getting no where (and the limits.h file does exist where it says it doesn't).  Would love to get this up and running on my mac if you have any ideas.

> building 'lsh.cMinhash' extension
> gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/admin/anaconda3/include -arch x86_64 -I/Users/admin/anaconda3/include -arch x86_64 -Ilsh -I/Users/admin/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/Users/admin/anaconda3/include/python3.6m -c lsh/cMinhash.cpp -o build/temp.macosx-10.7-x86_64-3.6/lsh/cMinhash.o
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
> In file included from /Users/admin/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
>                  from /Users/admin/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
>                  from /Users/admin/anaconda3/include/python3.6m/Python.h:11,
>                  from lsh/cMinhash.cpp:27:
> /Users/admin/anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
>  #include_next <limits.h>  /* recurse down to the real one */
>                                                              ^
> compilation terminated.
> error: command 'gcc' failed with exit status 1

**Comment by EggsBenedict** [comment]
FWIW, i tried this on an Ubuntu installation... I was able to cross the hurdle above apparently, but got nailed by the following.  I wonder if a specific version of GCC is required?

> ~/LSH$ python setup.py install
running install
running bdist_egg
running egg_info
writing lsh.egg-info/PKG-INFO
writing dependency_links to lsh.egg-info/dependency_links.txt
writing requirements to lsh.egg-info/requires.txt
writing top-level names to lsh.egg-info/top_level.txt
reading manifest file 'lsh.egg-info/SOURCES.txt'
writing manifest file 'lsh.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'lsh.cMinhash' extension
gcc -pthread -B /home/bgoddard/anaconda3_ubuntu/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/bgoddard/anaconda3_ubuntu/lib/python3.7/site-packages/numpy/core/include -I/home/bgoddard/anaconda3_ubuntu/include/python3.7m -c lsh/cMinhash.cpp -o build/temp.linux-x86_64-3.7/lsh/cMinhash.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/bgoddard/anaconda3_ubuntu/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1823:0,
                 from /home/bgoddard/anaconda3_ubuntu/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/bgoddard/anaconda3_ubuntu/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from lsh/cMinhash.cpp:304:
/home/bgoddard/anaconda3_ubuntu/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
lsh/cMinhash.cpp: In function ‘void __Pyx__ExceptionSave(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
lsh/cMinhash.cpp:19292:21: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     *type = tstate->exc_type;
                     ^~~~~~~~
                     curexc_type
lsh/cMinhash.cpp:19293:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     *value = tstate->exc_value;
                      ^~~~~~~~~
                      curexc_value
lsh/cMinhash.cpp:19294:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     *tb = tstate->exc_traceback;
                   ^~~~~~~~~~~~~
                   curexc_traceback
lsh/cMinhash.cpp: In function ‘void __Pyx__ExceptionReset(PyThreadState*, PyObject*, PyObject*, PyObject*)’:
lsh/cMinhash.cpp:19301:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tmp_type = tstate->exc_type;
                        ^~~~~~~~
                        curexc_type
lsh/cMinhash.cpp:19302:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tmp_value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
lsh/cMinhash.cpp:19303:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tmp_tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
lsh/cMinhash.cpp:19304:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tstate->exc_type = type;
             ^~~~~~~~
             curexc_type
lsh/cMinhash.cpp:19305:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tstate->exc_value = value;
             ^~~~~~~~~
             curexc_value
lsh/cMinhash.cpp:19306:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tstate->exc_traceback = tb;
             ^~~~~~~~~~~~~
             curexc_traceback
lsh/cMinhash.cpp: In function ‘int __Pyx__GetException(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
lsh/cMinhash.cpp:19361:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tmp_type = tstate->exc_type;
                        ^~~~~~~~
                        curexc_type
lsh/cMinhash.cpp:19362:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tmp_value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
lsh/cMinhash.cpp:19363:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tmp_tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
lsh/cMinhash.cpp:19364:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tstate->exc_type = local_type;
             ^~~~~~~~
             curexc_type
lsh/cMinhash.cpp:19365:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tstate->exc_value = local_value;
             ^~~~~~~~~
             curexc_value
lsh/cMinhash.cpp:19366:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tstate->exc_traceback = local_tb;
             ^~~~~~~~~~~~~
             curexc_traceback
lsh/cMinhash.cpp: In function ‘void __Pyx__ExceptionSwap(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
lsh/cMinhash.cpp:19388:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tmp_type = tstate->exc_type;
                        ^~~~~~~~
                        curexc_type
lsh/cMinhash.cpp:19389:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tmp_value = tstate->exc_value;
                         ^~~~~~~~~
                         curexc_value
lsh/cMinhash.cpp:19390:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tmp_tb = tstate->exc_traceback;
                      ^~~~~~~~~~~~~
                      curexc_traceback
lsh/cMinhash.cpp:19391:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
     tstate->exc_type = *type;
             ^~~~~~~~
             curexc_type
lsh/cMinhash.cpp:19392:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
     tstate->exc_value = *value;
             ^~~~~~~~~
             curexc_value
lsh/cMinhash.cpp:19393:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
     tstate->exc_traceback = *tb;
             ^~~~~~~~~~~~~
             curexc_traceback
In file included from /home/bgoddard/anaconda3_ubuntu/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:27:0,
                 from /home/bgoddard/anaconda3_ubuntu/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from lsh/cMinhash.cpp:304:
/home/bgoddard/anaconda3_ubuntu/lib/python3.7/site-packages/numpy/core/include/numpy/__multiarray_api.h: At global scope:
/home/bgoddard/anaconda3_ubuntu/lib/python3.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1463:1: warning: ‘int _import_array()’ defined but not used [-Wunused-function]
 _import_array(void)
 ^~~~~~~~~~~~~
error: command 'gcc' failed with exit status 1

**Comment by EggsBenedict** [comment]
If someone has a successful install on a OS X it would be great if you could report the version of OS, Anaconda, GCC you're using.  Reinstalled on windows just fine but can't get this loaded on MacOS / Ubuntu successfully.

**Comment by EggsBenedict** [comment]
FYI: did a fresh install of Ubuntu + Anaconda AND a different install method and so far so good.

After basic configuration of Ubuntu - including the basic, post conda install:
 `export PATH="/home/virtual/anaconda3/bin:$PATH"`

Installed via:
`pip install -e git+https://github.com/mattilyra/LSH.git#egg=lsh`

Used PIP install and things seemed to go just fine.  Still not sure why it doesn't work on my Mac yet, but I'll keep pursuing that.

Some info:

- Downloaded: Anaconda3-5.2.0-Linux-x86_64.sh from: [Continuum Archive](https://repo.continuum.io/archive/)
  - `python` should load up: Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) [GCC 7.2.0] on linux
- Distributor ID:	Ubuntu
   - Description:	Ubuntu 18.04.1 LTS
   - Release:	18.04
   - Codename:	bionic

Whew! Was really worried this wasn't going to work on a Ubuntu box which would be sad.

**Comment by EggsBenedict** [comment]
HOLY COW. FINALLY.
I think this was a GCC issue. All sorts of postings said: `xcode-select --install` which *does not* work for *Mojave*.  I think Anaconda's gcc is ancient or something for OS X installs as the Ubuntu one seemed fine.  I installed xcode command line tools several times, etc.. etc.. uninstalled gcc, reinstalled gcc, installed newer gcc versions but was never able to get Anaconda to recognize them.  On and on and on.  THIS was the only thing that worked: 

`sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`

**Comment by etoilestar** [comment]
so, how to resolve this problem?
